2018-02-22 11:53:41,601 p=17917 u=nikolai |   [WARNING]: module - not found in: /home/nikolai/.ansible/plugins/modules:/usr/
share/ansible/plugins/modules:/usr/lib/python2.7/dist-packages/ansible/modules

2018-02-22 11:53:41,602 p=17917 u=nikolai |   [WARNING]: module ansible.cfg not found in: /home/nikolai/.ansible/plugins/mod
ules:/usr/share/ansible/plugins/modules:/usr/lib/python2.7/dist-
packages/ansible/modules

2018-02-22 11:53:41,602 p=17917 u=nikolai |   [WARNING]: module ansible.log not found in: /home/nikolai/.ansible/plugins/mod
ules:/usr/share/ansible/plugins/modules:/usr/lib/python2.7/dist-
packages/ansible/modules

2018-02-22 11:53:41,602 p=17917 u=nikolai |   [WARNING]: module group_vars not found in: /home/nikolai/.ansible/plugins/modu
les:/usr/share/ansible/plugins/modules:/usr/lib/python2.7/dist-
packages/ansible/modules

2018-02-22 11:53:41,602 p=17917 u=nikolai |   [WARNING]: module inventory not found in: /home/nikolai/.ansible/plugins/modul
es:/usr/share/ansible/plugins/modules:/usr/lib/python2.7/dist-
packages/ansible/modules

2018-02-22 11:53:41,602 p=17917 u=nikolai |   [WARNING]: module main.yml not found in: /home/nikolai/.ansible/plugins/module
s:/usr/share/ansible/plugins/modules:/usr/lib/python2.7/dist-
packages/ansible/modules

2018-02-22 11:53:41,603 p=17917 u=nikolai |   [WARNING]: module roles not found in: /home/nikolai/.ansible/plugins/modules:/
usr/share/ansible/plugins/modules:/usr/lib/python2.7/dist-
packages/ansible/modules

2018-02-22 11:53:41,603 p=17917 u=nikolai |   [WARNING]: module ssh.cfg not found in: /home/nikolai/.ansible/plugins/modules
:/usr/share/ansible/plugins/modules:/usr/lib/python2.7/dist-
packages/ansible/modules

2018-02-22 11:56:47,173 p=21168 u=nikolai |  PLAY [install AD, create users, install SSHD service] *****************************************************************
2018-02-22 11:56:47,186 p=21168 u=nikolai |  TASK [Gathering Facts] ************************************************************************************************
2018-02-22 11:56:47,249 urllib3.connectionpool Starting new HTTPS connection (1): ad1.d91d.internal
2018-02-22 11:56:47,439 p=21168 u=nikolai |  fatal: [ad1.d91d.internal]: UNREACHABLE! => {
    "changed": false, 
    "unreachable": true
}

MSG:

basic: HTTPSConnectionPool(host='ad1.d91d.internal', port=5986): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0f264aec50>: Failed to establish a new connection: [Errno -2] Name or service not known',))

2018-02-22 11:56:47,441 p=21168 u=nikolai |  PLAY RECAP ************************************************************************************************************
2018-02-22 11:56:47,442 p=21168 u=nikolai |  ad1.d91d.internal          : ok=0    changed=0    unreachable=1    failed=0   
2018-02-22 11:57:37,620 p=22147 u=nikolai |  PLAY [install AD, create users, install SSHD service] *****************************************************************
2018-02-22 11:57:37,629 p=22147 u=nikolai |  TASK [Gathering Facts] ************************************************************************************************
2018-02-22 11:57:37,675 urllib3.connectionpool Starting new HTTPS connection (1): ad1.d91d.internal
2018-02-22 11:57:37,680 p=22147 u=nikolai |  fatal: [ad1.d91d.internal]: UNREACHABLE! => {
    "changed": false, 
    "unreachable": true
}

MSG:

basic: HTTPSConnectionPool(host='ad1.d91d.internal', port=5986): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7435e55c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))

2018-02-22 11:57:37,680 p=22147 u=nikolai |  PLAY RECAP ************************************************************************************************************
2018-02-22 11:57:37,681 p=22147 u=nikolai |  ad1.d91d.internal          : ok=0    changed=0    unreachable=1    failed=0   
2018-02-22 11:57:55,373 p=22495 u=nikolai |  PLAY [install AD, create users, install SSHD service] *****************************************************************
2018-02-22 11:57:55,383 p=22495 u=nikolai |  TASK [win-ad : install Windows AD] ************************************************************************************
2018-02-22 11:57:55,435 urllib3.connectionpool Starting new HTTPS connection (1): ad1.d91d.internal
2018-02-22 11:57:55,439 p=22495 u=nikolai |  fatal: [ad1.d91d.internal]: UNREACHABLE! => {
    "changed": false, 
    "unreachable": true
}

MSG:

basic: HTTPSConnectionPool(host='ad1.d91d.internal', port=5986): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f89b972d090>: Failed to establish a new connection: [Errno -2] Name or service not known',))

2018-02-22 11:57:55,440 p=22495 u=nikolai |  PLAY RECAP ************************************************************************************************************
2018-02-22 11:57:55,440 p=22495 u=nikolai |  ad1.d91d.internal          : ok=0    changed=0    unreachable=1    failed=0   
2018-02-22 11:59:32,416 p=24226 u=nikolai |  PLAY [install AD, create users, install SSHD service] *****************************************************************
2018-02-22 11:59:32,425 p=24226 u=nikolai |  TASK [win-ad : install Windows AD] ************************************************************************************
2018-02-22 11:59:32,474 urllib3.connectionpool Starting new HTTPS connection (1): ad1.d91d.example.opentlc.com
2018-02-22 11:59:33,645 urllib3.connectionpool https://ad1.d91d.example.opentlc.com:5986 "POST /wsman HTTP/1.1" 200 1629
2018-02-22 11:59:33,853 urllib3.connectionpool https://ad1.d91d.example.opentlc.com:5986 "POST /wsman HTTP/1.1" 200 847
2018-02-22 11:59:34,470 urllib3.connectionpool https://ad1.d91d.example.opentlc.com:5986 "POST /wsman HTTP/1.1" 200 753
2018-02-22 12:00:02,581 urllib3.connectionpool https://ad1.d91d.example.opentlc.com:5986 "POST /wsman HTTP/1.1" 500 1320
2018-02-22 12:00:22,801 urllib3.connectionpool https://ad1.d91d.example.opentlc.com:5986 "POST /wsman HTTP/1.1" 500 1320
2018-02-22 12:00:43,021 urllib3.connectionpool https://ad1.d91d.example.opentlc.com:5986 "POST /wsman HTTP/1.1" 500 1320
2018-02-22 12:01:03,275 urllib3.connectionpool https://ad1.d91d.example.opentlc.com:5986 "POST /wsman HTTP/1.1" 500 1320
2018-02-22 12:01:23,492 urllib3.connectionpool https://ad1.d91d.example.opentlc.com:5986 "POST /wsman HTTP/1.1" 500 1320
2018-02-22 12:01:43,709 urllib3.connectionpool https://ad1.d91d.example.opentlc.com:5986 "POST /wsman HTTP/1.1" 500 1320
2018-02-22 12:02:03,930 urllib3.connectionpool https://ad1.d91d.example.opentlc.com:5986 "POST /wsman HTTP/1.1" 500 1320
2018-02-22 12:02:24,148 urllib3.connectionpool https://ad1.d91d.example.opentlc.com:5986 "POST /wsman HTTP/1.1" 500 1320
2018-02-22 12:02:44,368 urllib3.connectionpool https://ad1.d91d.example.opentlc.com:5986 "POST /wsman HTTP/1.1" 500 1320
2018-02-22 12:03:04,591 urllib3.connectionpool https://ad1.d91d.example.opentlc.com:5986 "POST /wsman HTTP/1.1" 500 1320
2018-02-22 12:03:14,755 urllib3.connectionpool https://ad1.d91d.example.opentlc.com:5986 "POST /wsman HTTP/1.1" 200 2747
2018-02-22 12:03:14,964 urllib3.connectionpool https://ad1.d91d.example.opentlc.com:5986 "POST /wsman HTTP/1.1" 200 757
2018-02-22 12:03:15,173 urllib3.connectionpool https://ad1.d91d.example.opentlc.com:5986 "POST /wsman HTTP/1.1" 200 602
2018-02-22 12:03:15,189 p=24226 u=nikolai |  ERROR! The requested handler 'reboot_required' was not found in either the main handlers list nor in the listening handlers list
